version: '3.3'
services: 
    web:
        restart: unless-stopped
        depends_on:
            - db
        build: 
            context: ./
            dockerfile: Dockerfile
            args:
                app_env: dev
        ports: 
            - "8080:8080"
        volumes: 
            - ./app:/go/src/myproject/app
    db:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE : 'mydb'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - 3306:3306
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db: